version: "3"

services:
  integration-test:
    build:
      context: .
      dockerfile: Dockerfile.integration
    volumes:
      - ./test-logs:/app/logs
    environment:
      - VECFS_FILE=/app/data/test-vecfs-data.jsonl
  http-integration-test:
    build:
      context: .
      dockerfile: Dockerfile.integration
    volumes:
      - ./test-logs:/app/logs
    environment:
      - VECFS_FILE=/app/data/http-test-vecfs-data.jsonl
    command: npm run test:http
