baseURL = "https://wazzamo.github.io/vecfs/"
languageCode = "en-us"
title = "VecFS"
theme = "github.com/alex-shpak/hugo-book"
publishDir = "public"

[module]
  [[module.imports]]
    path = "github.com/alex-shpak/hugo-book"
    disable = false

[params]
  BookTheme = "auto"
  BookToC = true
  BookLogo = "logo.svg"
  BookSection = "docs"
  BookSearch = true
  BookComments = false
  [params.author]
    name = "VecFS"
    website = "https://github.com/WazzaMo/vecfs"
    github = "WazzaMo/vecfs"

[outputs]
  home = ["HTML", "RSS"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = false
    noClasses = false
    style = "github"
    tabWidth = 4
